version: 2.1

jobs:
    performance-report:
        docker:
            - image: circleci/node:latest
        
        resource_class: small

        steps:
            - checkout
            - restore_cache:
                keys:
                  - npm-report-{{ checksum "package.json" }}
                  - npm-report-
            - run:
                name: Install JS dependencies
                command: npm i
            - save_cache:
                key: npm-report-{{ checksum "package.json" }}
                paths:
                  - ".circleci/node_modules"
            - run:
                name: Generate Performance / Accessibility report
                command: node perf_report.js

    age-report:
        docker:
            - image: circleci/node:latest
        
        resource_class: small

        steps:
            - checkout
            - restore_cache:
                keys:
                  - npm-report-{{ checksum "package.json" }}
                  - npm-report-
            - run:
                name: Install JS dependencies
                command: npm i
            - save_cache:
                key: npm-report-{{ checksum "package.json" }}
                paths:
                  - ".circleci/node_modules"
            - run:
                name: Generate Ticket Age report
                command: node age_report.js

    component-report:
        docker:
            - image: circleci/node:latest
        
        resource_class: small

        steps:
            - checkout
            - restore_cache:
                keys:
                  - npm-report-{{ checksum "package.json" }}
                  - npm-report-
            - run:
                name: Install JS dependencies
                command: npm i
            - save_cache:
                key: npm-report-{{ checksum "package.json" }}
                paths:
                  - ".circleci/node_modules"
            - run:
                name: Generate component report
                command: node component_report.js

    security-report:
        docker:
            - image: circleci/node:latest
        
        resource_class: small

        steps:
            - checkout
            - restore_cache:
                keys:
                  - npm-report-{{ checksum "package.json" }}
                  - npm-report-
            - run:
                name: Install JS dependencies
                command: npm i
            - save_cache:
                key: npm-report-{{ checksum "package.json" }}
                paths:
                  - ".circleci/node_modules"
            - run:
                name: Generate component report
                command: node security_report.js
    
    standards-report:
        docker:
            - image: circleci/node:latest
        
        resource_class: small

        steps:
            - checkout
            - restore_cache:
                keys:
                  - npm-report-{{ checksum "package.json" }}
                  - npm-report-
            - run:
                name: Install JS dependencies
                command: npm i
            - save_cache:
                key: npm-report-{{ checksum "package.json" }}
                paths:
                  - ".circleci/node_modules"
            - run:
                name: Generate component report
                command: node standards_report.js

workflows:
    version: 2

    ad-hoc:
        jobs:
            - performance-report:
                filters:
                    branches:
                      only:
                        - main
            - age-report:
                filters:
                    branches:
                      only:
                        - main
            - component-report:
                filters:
                    branches:
                      only:
                        - main
            - security-report:
                filters:
                    branches:
                      only:
                        - main
            - standards-report:
                filters:
                    branches:
                      only:
                        - main
    
    sunday-reports:
        triggers:
            - schedule:
                cron: "0 7 * * 0"
                filters:
                    branches:
                      only:
                        - main
        jobs:
            - performance-report
            - age-report
            - component-report
            - security-report
            - standards-report
